language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t alexluyz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexluyz/docker-react npm run test